
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.UIManager UIManager;

	private global::Gtk.Action FileAction;

	private global::Gtk.Action QuitAction;

	private global::Gtk.Action PreferencesAction;

	private global::Gtk.RadioAction NoRoundingOffAction;

	private global::Gtk.RadioAction WholeNumberAction;

	private global::Gtk.RadioAction DecimalPlaceAction1;

	private global::Gtk.RadioAction DecimalPlacesAction2;

	private global::Gtk.RadioAction DecimalPlacesAction3;

	private global::Gtk.RadioAction DecimalPlacesAction4;

	private global::Gtk.RadioAction DecimalPlacesAction5;

	private global::Gtk.RadioAction DecimalPlacesAction6;

	private global::Gtk.RadioAction DecimalPlacesAction7;

	private global::Gtk.RadioAction DecimalPlacesAction8;

	private global::Gtk.RadioAction DecimalPlacesAction9;

	private global::Gtk.RadioAction DecimalPlacesAction10;

	private global::Gtk.Action AboutAction;

	private global::Gtk.Action AboutUnitConverterAction;

	private global::Gtk.VBox MainArea;

	private global::Gtk.MenuBar MenuBar;

	private global::Gtk.HBox MainConversionArea;

	private global::Gtk.ScrolledWindow GtkScrolledWindow;

	private global::Gtk.VButtonBox QuantityPicker;

	private global::Gtk.Button LengthSelector;

	private global::Gtk.Button AreaSelector;

	private global::Gtk.Button VolumeSelector;

	private global::Gtk.Button TimeSelector;

	private global::Gtk.Button SpeedSelector;

	private global::Gtk.Button FlowAreaSelector;

	private global::Gtk.Button FlowVolumeSelector;

	private global::Gtk.Button FlowMassSelector;

	private global::Gtk.Button MassSelector;

	private global::Gtk.Button EnergySelector;

	private global::Gtk.Button PressureSelector;

	private global::Gtk.Button TemperatureSelector;

	private global::Gtk.Button LuminanceSelector;

	private global::Gtk.Button IlluminanceSelector;

	private global::Gtk.Button AngleSelector;

	private global::Gtk.Button DataSizeSelector;

	private global::Gtk.VBox ConversionAreaA;

	private global::Gtk.ComboBox FromUnitPicker;

	private global::Gtk.Entry InputBox;

	private global::Gtk.Button ClearButton;

	private global::Gtk.VBox ConversionAreaB;

	private global::Gtk.ComboBox ToUnitPicker;

	private global::Gtk.Entry OutputBox;

	private global::Gtk.Button SwapButton;

	private global::Gtk.Statusbar StatusBar;

	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.UIManager = new global::Gtk.UIManager();
		global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup("Default");
		this.FileAction = new global::Gtk.Action("FileAction", "_File", null, null);
		this.FileAction.ShortLabel = "_File";
		w1.Add(this.FileAction, null);
		this.QuitAction = new global::Gtk.Action("QuitAction", "_Quit", null, null);
		this.QuitAction.ShortLabel = "_Quit";
		w1.Add(this.QuitAction, "<Primary><Mod2>q");
		this.PreferencesAction = new global::Gtk.Action("PreferencesAction", "_Preferences", null, null);
		this.PreferencesAction.ShortLabel = "_Preferences";
		w1.Add(this.PreferencesAction, null);
		this.NoRoundingOffAction = new global::Gtk.RadioAction("NoRoundingOffAction", "_No Rounding Off", null, null, 0);
		this.NoRoundingOffAction.Group = new global::GLib.SList(global::System.IntPtr.Zero);
		this.NoRoundingOffAction.ShortLabel = "_No Rounding Off";
		w1.Add(this.NoRoundingOffAction, "<Primary><Alt><Mod2>n");
		this.WholeNumberAction = new global::Gtk.RadioAction("WholeNumberAction", "_Whole Number", null, null, 0);
		this.WholeNumberAction.Group = this.NoRoundingOffAction.Group;
		this.WholeNumberAction.ShortLabel = "_Whole Number";
		w1.Add(this.WholeNumberAction, "<Primary><Alt><Mod2>w");
		this.DecimalPlaceAction1 = new global::Gtk.RadioAction("DecimalPlaceAction1", "_1 Decimal Place", null, null, 0);
		this.DecimalPlaceAction1.Group = this.WholeNumberAction.Group;
		this.DecimalPlaceAction1.ShortLabel = "_1 Decimal Place";
		w1.Add(this.DecimalPlaceAction1, "<Primary><Alt><Mod2>1");
		this.DecimalPlacesAction2 = new global::Gtk.RadioAction("DecimalPlacesAction2", "_2 Decimal Places", null, null, 0);
		this.DecimalPlacesAction2.Group = this.WholeNumberAction.Group;
		this.DecimalPlacesAction2.ShortLabel = "_2 Decimal Places";
		w1.Add(this.DecimalPlacesAction2, "<Primary><Alt><Mod2>2");
		this.DecimalPlacesAction3 = new global::Gtk.RadioAction("DecimalPlacesAction3", "_3 Decimal Places", null, null, 0);
		this.DecimalPlacesAction3.Group = this.WholeNumberAction.Group;
		this.DecimalPlacesAction3.ShortLabel = "_3 Decimal Places";
		w1.Add(this.DecimalPlacesAction3, "<Primary><Alt><Mod2>3");
		this.DecimalPlacesAction4 = new global::Gtk.RadioAction("DecimalPlacesAction4", "_4 Decimal Places", null, null, 0);
		this.DecimalPlacesAction4.Group = this.WholeNumberAction.Group;
		this.DecimalPlacesAction4.ShortLabel = "_4 Decimal Places";
		w1.Add(this.DecimalPlacesAction4, "<Primary><Alt><Mod2>4");
		this.DecimalPlacesAction5 = new global::Gtk.RadioAction("DecimalPlacesAction5", "_5 Decimal Places", null, null, 0);
		this.DecimalPlacesAction5.Group = this.WholeNumberAction.Group;
		this.DecimalPlacesAction5.ShortLabel = "_5 Decimal Places";
		w1.Add(this.DecimalPlacesAction5, "<Primary><Alt><Mod2>5");
		this.DecimalPlacesAction6 = new global::Gtk.RadioAction("DecimalPlacesAction6", "_6 Decimal Places", null, null, 0);
		this.DecimalPlacesAction6.Group = this.WholeNumberAction.Group;
		this.DecimalPlacesAction6.ShortLabel = "_6 Decimal Places";
		w1.Add(this.DecimalPlacesAction6, "<Primary><Alt><Mod2>6");
		this.DecimalPlacesAction7 = new global::Gtk.RadioAction("DecimalPlacesAction7", "_7 Decimal Places", null, null, 0);
		this.DecimalPlacesAction7.Group = this.WholeNumberAction.Group;
		this.DecimalPlacesAction7.ShortLabel = "_7 Decimal Places";
		w1.Add(this.DecimalPlacesAction7, "<Primary><Alt><Mod2>7");
		this.DecimalPlacesAction8 = new global::Gtk.RadioAction("DecimalPlacesAction8", "_8 Decimal Places", null, null, 0);
		this.DecimalPlacesAction8.Group = this.WholeNumberAction.Group;
		this.DecimalPlacesAction8.ShortLabel = "_8 Decimal Places";
		w1.Add(this.DecimalPlacesAction8, "<Primary><Alt><Mod2>8");
		this.DecimalPlacesAction9 = new global::Gtk.RadioAction("DecimalPlacesAction9", "_9 Decimal Places", null, null, 0);
		this.DecimalPlacesAction9.Group = this.WholeNumberAction.Group;
		this.DecimalPlacesAction9.ShortLabel = "_9 Decimal Places";
		w1.Add(this.DecimalPlacesAction9, "<Primary><Alt><Mod2>9");
		this.DecimalPlacesAction10 = new global::Gtk.RadioAction("DecimalPlacesAction10", "1_0 Decimal Places", null, null, 0);
		this.DecimalPlacesAction10.Group = this.WholeNumberAction.Group;
		this.DecimalPlacesAction10.ShortLabel = "1_0 Decimal Places";
		w1.Add(this.DecimalPlacesAction10, "<Primary><Alt><Mod2>0");
		this.AboutAction = new global::Gtk.Action("AboutAction", "_About", null, null);
		this.AboutAction.ShortLabel = "_About";
		w1.Add(this.AboutAction, null);
		this.AboutUnitConverterAction = new global::Gtk.Action("AboutUnitConverterAction", "About _Unit Converter", null, null);
		this.AboutUnitConverterAction.ShortLabel = "About _Unit Converter";
		w1.Add(this.AboutUnitConverterAction, null);
		this.UIManager.InsertActionGroup(w1, 0);
		this.AddAccelGroup(this.UIManager.AccelGroup);
		this.Name = "MainWindow";
		this.Title = "Unit Converter";
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		this.Resizable = false;
		this.AllowGrow = false;
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.MainArea = new global::Gtk.VBox();
		this.MainArea.Name = "MainArea";
		this.MainArea.Spacing = 6;
		// Container child MainArea.Gtk.Box+BoxChild
		this.UIManager.AddUiFromString(@"<ui><menubar name='MenuBar'><menu name='FileAction' action='FileAction'><menuitem name='QuitAction' action='QuitAction'/></menu><menu name='PreferencesAction' action='PreferencesAction'><menuitem name='NoRoundingOffAction' action='NoRoundingOffAction'/><menuitem name='WholeNumberAction' action='WholeNumberAction'/><menuitem name='DecimalPlaceAction1' action='DecimalPlaceAction1'/><menuitem name='DecimalPlacesAction2' action='DecimalPlacesAction2'/><menuitem name='DecimalPlacesAction3' action='DecimalPlacesAction3'/><menuitem name='DecimalPlacesAction4' action='DecimalPlacesAction4'/><menuitem name='DecimalPlacesAction5' action='DecimalPlacesAction5'/><menuitem name='DecimalPlacesAction6' action='DecimalPlacesAction6'/><menuitem name='DecimalPlacesAction7' action='DecimalPlacesAction7'/><menuitem name='DecimalPlacesAction8' action='DecimalPlacesAction8'/><menuitem name='DecimalPlacesAction9' action='DecimalPlacesAction9'/><menuitem name='DecimalPlacesAction10' action='DecimalPlacesAction10'/></menu><menu name='AboutAction' action='AboutAction'><menuitem name='AboutUnitConverterAction' action='AboutUnitConverterAction'/></menu></menubar></ui>");
		this.MenuBar = ((global::Gtk.MenuBar)(this.UIManager.GetWidget("/MenuBar")));
		this.MenuBar.Name = "MenuBar";
		this.MainArea.Add(this.MenuBar);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.MainArea[this.MenuBar]));
		w2.Position = 0;
		w2.Expand = false;
		w2.Fill = false;
		// Container child MainArea.Gtk.Box+BoxChild
		this.MainConversionArea = new global::Gtk.HBox();
		this.MainConversionArea.Name = "MainConversionArea";
		this.MainConversionArea.Spacing = 6;
		// Container child MainConversionArea.Gtk.Box+BoxChild
		this.GtkScrolledWindow = new global::Gtk.ScrolledWindow();
		this.GtkScrolledWindow.WidthRequest = 120;
		this.GtkScrolledWindow.HeightRequest = 208;
		this.GtkScrolledWindow.Name = "GtkScrolledWindow";
		this.GtkScrolledWindow.HscrollbarPolicy = ((global::Gtk.PolicyType)(2));
		this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
		global::Gtk.Viewport w3 = new global::Gtk.Viewport();
		w3.ShadowType = ((global::Gtk.ShadowType)(0));
		// Container child GtkViewport.Gtk.Container+ContainerChild
		this.QuantityPicker = new global::Gtk.VButtonBox();
		this.QuantityPicker.Name = "QuantityPicker";
		this.QuantityPicker.Homogeneous = true;
		// Container child QuantityPicker.Gtk.ButtonBox+ButtonBoxChild
		this.LengthSelector = new global::Gtk.Button();
		this.LengthSelector.CanFocus = true;
		this.LengthSelector.Name = "LengthSelector";
		this.LengthSelector.UseUnderline = true;
		this.LengthSelector.Label = "Length";
		this.QuantityPicker.Add(this.LengthSelector);
		global::Gtk.ButtonBox.ButtonBoxChild w4 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.QuantityPicker[this.LengthSelector]));
		w4.Expand = false;
		w4.Fill = false;
		// Container child QuantityPicker.Gtk.ButtonBox+ButtonBoxChild
		this.AreaSelector = new global::Gtk.Button();
		this.AreaSelector.CanFocus = true;
		this.AreaSelector.Name = "AreaSelector";
		this.AreaSelector.UseUnderline = true;
		this.AreaSelector.Label = "Area";
		this.QuantityPicker.Add(this.AreaSelector);
		global::Gtk.ButtonBox.ButtonBoxChild w5 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.QuantityPicker[this.AreaSelector]));
		w5.Position = 1;
		w5.Expand = false;
		w5.Fill = false;
		// Container child QuantityPicker.Gtk.ButtonBox+ButtonBoxChild
		this.VolumeSelector = new global::Gtk.Button();
		this.VolumeSelector.CanFocus = true;
		this.VolumeSelector.Name = "VolumeSelector";
		this.VolumeSelector.UseUnderline = true;
		this.VolumeSelector.Label = "Volume";
		this.QuantityPicker.Add(this.VolumeSelector);
		global::Gtk.ButtonBox.ButtonBoxChild w6 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.QuantityPicker[this.VolumeSelector]));
		w6.Position = 2;
		w6.Expand = false;
		w6.Fill = false;
		// Container child QuantityPicker.Gtk.ButtonBox+ButtonBoxChild
		this.TimeSelector = new global::Gtk.Button();
		this.TimeSelector.CanFocus = true;
		this.TimeSelector.Name = "TimeSelector";
		this.TimeSelector.UseUnderline = true;
		this.TimeSelector.Label = "Time";
		this.QuantityPicker.Add(this.TimeSelector);
		global::Gtk.ButtonBox.ButtonBoxChild w7 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.QuantityPicker[this.TimeSelector]));
		w7.Position = 3;
		w7.Expand = false;
		w7.Fill = false;
		// Container child QuantityPicker.Gtk.ButtonBox+ButtonBoxChild
		this.SpeedSelector = new global::Gtk.Button();
		this.SpeedSelector.CanFocus = true;
		this.SpeedSelector.Name = "SpeedSelector";
		this.SpeedSelector.UseUnderline = true;
		this.SpeedSelector.Label = "Speed";
		this.QuantityPicker.Add(this.SpeedSelector);
		global::Gtk.ButtonBox.ButtonBoxChild w8 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.QuantityPicker[this.SpeedSelector]));
		w8.Position = 4;
		w8.Expand = false;
		w8.Fill = false;
		// Container child QuantityPicker.Gtk.ButtonBox+ButtonBoxChild
		this.FlowAreaSelector = new global::Gtk.Button();
		this.FlowAreaSelector.CanFocus = true;
		this.FlowAreaSelector.Name = "FlowAreaSelector";
		this.FlowAreaSelector.UseUnderline = true;
		this.FlowAreaSelector.Label = "Flow Area";
		this.QuantityPicker.Add(this.FlowAreaSelector);
		global::Gtk.ButtonBox.ButtonBoxChild w9 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.QuantityPicker[this.FlowAreaSelector]));
		w9.Position = 5;
		w9.Expand = false;
		w9.Fill = false;
		// Container child QuantityPicker.Gtk.ButtonBox+ButtonBoxChild
		this.FlowVolumeSelector = new global::Gtk.Button();
		this.FlowVolumeSelector.CanFocus = true;
		this.FlowVolumeSelector.Name = "FlowVolumeSelector";
		this.FlowVolumeSelector.UseUnderline = true;
		this.FlowVolumeSelector.Label = "Flow Volume";
		this.QuantityPicker.Add(this.FlowVolumeSelector);
		global::Gtk.ButtonBox.ButtonBoxChild w10 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.QuantityPicker[this.FlowVolumeSelector]));
		w10.Position = 6;
		w10.Expand = false;
		w10.Fill = false;
		// Container child QuantityPicker.Gtk.ButtonBox+ButtonBoxChild
		this.FlowMassSelector = new global::Gtk.Button();
		this.FlowMassSelector.CanFocus = true;
		this.FlowMassSelector.Name = "FlowMassSelector";
		this.FlowMassSelector.UseUnderline = true;
		this.FlowMassSelector.Label = "Flow Mass";
		this.QuantityPicker.Add(this.FlowMassSelector);
		global::Gtk.ButtonBox.ButtonBoxChild w11 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.QuantityPicker[this.FlowMassSelector]));
		w11.Position = 7;
		w11.Expand = false;
		w11.Fill = false;
		// Container child QuantityPicker.Gtk.ButtonBox+ButtonBoxChild
		this.MassSelector = new global::Gtk.Button();
		this.MassSelector.CanFocus = true;
		this.MassSelector.Name = "MassSelector";
		this.MassSelector.UseUnderline = true;
		this.MassSelector.Label = "Mass";
		this.QuantityPicker.Add(this.MassSelector);
		global::Gtk.ButtonBox.ButtonBoxChild w12 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.QuantityPicker[this.MassSelector]));
		w12.Position = 8;
		w12.Expand = false;
		w12.Fill = false;
		// Container child QuantityPicker.Gtk.ButtonBox+ButtonBoxChild
		this.EnergySelector = new global::Gtk.Button();
		this.EnergySelector.CanFocus = true;
		this.EnergySelector.Name = "EnergySelector";
		this.EnergySelector.UseUnderline = true;
		this.EnergySelector.Label = "Energy";
		this.QuantityPicker.Add(this.EnergySelector);
		global::Gtk.ButtonBox.ButtonBoxChild w13 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.QuantityPicker[this.EnergySelector]));
		w13.Position = 9;
		w13.Expand = false;
		w13.Fill = false;
		// Container child QuantityPicker.Gtk.ButtonBox+ButtonBoxChild
		this.PressureSelector = new global::Gtk.Button();
		this.PressureSelector.CanFocus = true;
		this.PressureSelector.Name = "PressureSelector";
		this.PressureSelector.UseUnderline = true;
		this.PressureSelector.Label = "Pressure";
		this.QuantityPicker.Add(this.PressureSelector);
		global::Gtk.ButtonBox.ButtonBoxChild w14 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.QuantityPicker[this.PressureSelector]));
		w14.Position = 10;
		w14.Expand = false;
		w14.Fill = false;
		// Container child QuantityPicker.Gtk.ButtonBox+ButtonBoxChild
		this.TemperatureSelector = new global::Gtk.Button();
		this.TemperatureSelector.CanFocus = true;
		this.TemperatureSelector.Name = "TemperatureSelector";
		this.TemperatureSelector.UseUnderline = true;
		this.TemperatureSelector.Label = "Temperature";
		this.QuantityPicker.Add(this.TemperatureSelector);
		global::Gtk.ButtonBox.ButtonBoxChild w15 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.QuantityPicker[this.TemperatureSelector]));
		w15.Position = 11;
		w15.Expand = false;
		w15.Fill = false;
		// Container child QuantityPicker.Gtk.ButtonBox+ButtonBoxChild
		this.LuminanceSelector = new global::Gtk.Button();
		this.LuminanceSelector.CanFocus = true;
		this.LuminanceSelector.Name = "LuminanceSelector";
		this.LuminanceSelector.UseUnderline = true;
		this.LuminanceSelector.Label = "Luminance";
		this.QuantityPicker.Add(this.LuminanceSelector);
		global::Gtk.ButtonBox.ButtonBoxChild w16 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.QuantityPicker[this.LuminanceSelector]));
		w16.Position = 12;
		w16.Expand = false;
		w16.Fill = false;
		// Container child QuantityPicker.Gtk.ButtonBox+ButtonBoxChild
		this.IlluminanceSelector = new global::Gtk.Button();
		this.IlluminanceSelector.CanFocus = true;
		this.IlluminanceSelector.Name = "IlluminanceSelector";
		this.IlluminanceSelector.UseUnderline = true;
		this.IlluminanceSelector.Label = "Illuminance";
		this.QuantityPicker.Add(this.IlluminanceSelector);
		global::Gtk.ButtonBox.ButtonBoxChild w17 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.QuantityPicker[this.IlluminanceSelector]));
		w17.Position = 13;
		w17.Expand = false;
		w17.Fill = false;
		// Container child QuantityPicker.Gtk.ButtonBox+ButtonBoxChild
		this.AngleSelector = new global::Gtk.Button();
		this.AngleSelector.CanFocus = true;
		this.AngleSelector.Name = "AngleSelector";
		this.AngleSelector.UseUnderline = true;
		this.AngleSelector.Label = "Angle";
		this.QuantityPicker.Add(this.AngleSelector);
		global::Gtk.ButtonBox.ButtonBoxChild w18 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.QuantityPicker[this.AngleSelector]));
		w18.Position = 14;
		w18.Expand = false;
		w18.Fill = false;
		// Container child QuantityPicker.Gtk.ButtonBox+ButtonBoxChild
		this.DataSizeSelector = new global::Gtk.Button();
		this.DataSizeSelector.CanFocus = true;
		this.DataSizeSelector.Name = "DataSizeSelector";
		this.DataSizeSelector.UseUnderline = true;
		this.DataSizeSelector.Label = "Data Size";
		this.QuantityPicker.Add(this.DataSizeSelector);
		global::Gtk.ButtonBox.ButtonBoxChild w19 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.QuantityPicker[this.DataSizeSelector]));
		w19.Position = 15;
		w19.Expand = false;
		w19.Fill = false;
		w3.Add(this.QuantityPicker);
		this.GtkScrolledWindow.Add(w3);
		this.MainConversionArea.Add(this.GtkScrolledWindow);
		global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.MainConversionArea[this.GtkScrolledWindow]));
		w22.Position = 0;
		// Container child MainConversionArea.Gtk.Box+BoxChild
		this.ConversionAreaA = new global::Gtk.VBox();
		this.ConversionAreaA.Name = "ConversionAreaA";
		this.ConversionAreaA.Spacing = 6;
		// Container child ConversionAreaA.Gtk.Box+BoxChild
		this.FromUnitPicker = global::Gtk.ComboBox.NewText();
		this.FromUnitPicker.WidthRequest = 320;
		this.FromUnitPicker.Name = "FromUnitPicker";
		this.ConversionAreaA.Add(this.FromUnitPicker);
		global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(this.ConversionAreaA[this.FromUnitPicker]));
		w23.Position = 0;
		w23.Fill = false;
		// Container child ConversionAreaA.Gtk.Box+BoxChild
		this.InputBox = new global::Gtk.Entry();
		this.InputBox.CanFocus = true;
		this.InputBox.Name = "InputBox";
		this.InputBox.IsEditable = true;
		this.InputBox.InvisibleChar = '•';
		this.ConversionAreaA.Add(this.InputBox);
		global::Gtk.Box.BoxChild w24 = ((global::Gtk.Box.BoxChild)(this.ConversionAreaA[this.InputBox]));
		w24.Position = 1;
		w24.Expand = false;
		w24.Fill = false;
		// Container child ConversionAreaA.Gtk.Box+BoxChild
		this.ClearButton = new global::Gtk.Button();
		this.ClearButton.CanFocus = true;
		this.ClearButton.Name = "ClearButton";
		this.ClearButton.UseUnderline = true;
		this.ClearButton.Label = "_Clear";
		this.ConversionAreaA.Add(this.ClearButton);
		global::Gtk.Box.BoxChild w25 = ((global::Gtk.Box.BoxChild)(this.ConversionAreaA[this.ClearButton]));
		w25.Position = 2;
		w25.Expand = false;
		w25.Fill = false;
		this.MainConversionArea.Add(this.ConversionAreaA);
		global::Gtk.Box.BoxChild w26 = ((global::Gtk.Box.BoxChild)(this.MainConversionArea[this.ConversionAreaA]));
		w26.Position = 1;
		w26.Fill = false;
		// Container child MainConversionArea.Gtk.Box+BoxChild
		this.ConversionAreaB = new global::Gtk.VBox();
		this.ConversionAreaB.Name = "ConversionAreaB";
		this.ConversionAreaB.Spacing = 6;
		// Container child ConversionAreaB.Gtk.Box+BoxChild
		this.ToUnitPicker = global::Gtk.ComboBox.NewText();
		this.ToUnitPicker.WidthRequest = 320;
		this.ToUnitPicker.Name = "ToUnitPicker";
		this.ConversionAreaB.Add(this.ToUnitPicker);
		global::Gtk.Box.BoxChild w27 = ((global::Gtk.Box.BoxChild)(this.ConversionAreaB[this.ToUnitPicker]));
		w27.Position = 0;
		w27.Fill = false;
		// Container child ConversionAreaB.Gtk.Box+BoxChild
		this.OutputBox = new global::Gtk.Entry();
		this.OutputBox.CanFocus = true;
		this.OutputBox.Name = "OutputBox";
		this.OutputBox.IsEditable = false;
		this.OutputBox.InvisibleChar = '•';
		this.ConversionAreaB.Add(this.OutputBox);
		global::Gtk.Box.BoxChild w28 = ((global::Gtk.Box.BoxChild)(this.ConversionAreaB[this.OutputBox]));
		w28.Position = 1;
		w28.Expand = false;
		w28.Fill = false;
		// Container child ConversionAreaB.Gtk.Box+BoxChild
		this.SwapButton = new global::Gtk.Button();
		this.SwapButton.CanFocus = true;
		this.SwapButton.Name = "SwapButton";
		this.SwapButton.UseUnderline = true;
		this.SwapButton.Label = "_Swap";
		this.ConversionAreaB.Add(this.SwapButton);
		global::Gtk.Box.BoxChild w29 = ((global::Gtk.Box.BoxChild)(this.ConversionAreaB[this.SwapButton]));
		w29.Position = 2;
		w29.Expand = false;
		w29.Fill = false;
		this.MainConversionArea.Add(this.ConversionAreaB);
		global::Gtk.Box.BoxChild w30 = ((global::Gtk.Box.BoxChild)(this.MainConversionArea[this.ConversionAreaB]));
		w30.Position = 2;
		w30.Fill = false;
		this.MainArea.Add(this.MainConversionArea);
		global::Gtk.Box.BoxChild w31 = ((global::Gtk.Box.BoxChild)(this.MainArea[this.MainConversionArea]));
		w31.Position = 1;
		w31.Expand = false;
		w31.Fill = false;
		// Container child MainArea.Gtk.Box+BoxChild
		this.StatusBar = new global::Gtk.Statusbar();
		this.StatusBar.Name = "StatusBar";
		this.StatusBar.Spacing = 6;
		this.MainArea.Add(this.StatusBar);
		global::Gtk.Box.BoxChild w32 = ((global::Gtk.Box.BoxChild)(this.MainArea[this.StatusBar]));
		w32.Position = 2;
		w32.Expand = false;
		w32.Fill = false;
		this.Add(this.MainArea);
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.DefaultWidth = 772;
		this.DefaultHeight = 264;
		this.Show();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
		this.QuitAction.Activated += new global::System.EventHandler(this.QuitSelected);
		this.NoRoundingOffAction.Activated += new global::System.EventHandler(this.NoRoundingOffSelected);
		this.WholeNumberAction.Activated += new global::System.EventHandler(this.WholeNumberSelected);
		this.DecimalPlaceAction1.Activated += new global::System.EventHandler(this.DP1Selected);
		this.DecimalPlacesAction2.Activated += new global::System.EventHandler(this.DP2Selected);
		this.DecimalPlacesAction3.Activated += new global::System.EventHandler(this.DP3Selected);
		this.DecimalPlacesAction4.Activated += new global::System.EventHandler(this.DP4Selected);
		this.DecimalPlacesAction5.Activated += new global::System.EventHandler(this.DP5Selected);
		this.DecimalPlacesAction6.Activated += new global::System.EventHandler(this.DP6Selected);
		this.DecimalPlacesAction7.Activated += new global::System.EventHandler(this.DP7Selected);
		this.DecimalPlacesAction8.Activated += new global::System.EventHandler(this.DP8Selected);
		this.DecimalPlacesAction9.Activated += new global::System.EventHandler(this.DP9Selected);
		this.DecimalPlacesAction10.Activated += new global::System.EventHandler(this.DP10Selected);
		this.LengthSelector.Clicked += new global::System.EventHandler(this.LengthButtonClicked);
		this.AreaSelector.Clicked += new global::System.EventHandler(this.AreaButtonClicked);
		this.VolumeSelector.Clicked += new global::System.EventHandler(this.VolumeButtonClicked);
		this.TimeSelector.Clicked += new global::System.EventHandler(this.TimeButtonClicked);
		this.SpeedSelector.Clicked += new global::System.EventHandler(this.SpeedButtonClicked);
		this.FlowAreaSelector.Clicked += new global::System.EventHandler(this.FlowAreaButtonClicked);
		this.FlowVolumeSelector.Clicked += new global::System.EventHandler(this.FlowVolumeButtonClicked);
		this.FlowMassSelector.Clicked += new global::System.EventHandler(this.FlowMassButtonClicked);
		this.MassSelector.Clicked += new global::System.EventHandler(this.MassButtonClicked);
		this.EnergySelector.Clicked += new global::System.EventHandler(this.EnergyButtonClicked);
		this.PressureSelector.Clicked += new global::System.EventHandler(this.PressureButtonClicked);
		this.TemperatureSelector.Clicked += new global::System.EventHandler(this.TemperatureButtonClicked);
		this.LuminanceSelector.Clicked += new global::System.EventHandler(this.LuminanceButtonClicked);
		this.IlluminanceSelector.Clicked += new global::System.EventHandler(this.IlluminanceButtonClicked);
		this.AngleSelector.Clicked += new global::System.EventHandler(this.AngleButtonClicked);
		this.DataSizeSelector.Clicked += new global::System.EventHandler(this.DataSizeClick);
		this.FromUnitPicker.Changed += new global::System.EventHandler(this.InputBoxSelectedChanged);
		this.InputBox.TextInserted += new global::Gtk.TextInsertedHandler(this.InputTextInserted);
		this.InputBox.TextDeleted += new global::Gtk.TextDeletedHandler(this.InputTextDeleted);
		this.ClearButton.Clicked += new global::System.EventHandler(this.ClearButtonClicked);
		this.ToUnitPicker.Changed += new global::System.EventHandler(this.OutputBoxSelectedChanged);
		this.SwapButton.Clicked += new global::System.EventHandler(this.SwapButtonClicked);
	}
}
